# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def common_pods
   pod 'SwiftLint'
   pod 'SwipeCellKit'
   pod 'M13Checkbox'
   pod 'Alamofire', '~> 5.2'
   pod 'FloatingPanel'
   pod 'MarkdownKit'
end

target 'IssueTracker' do
  common_pods
end

target 'IssueTrackerNetworkTests' do
  common_pods
end
